name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies for React
        run: cd frontend/ && npm install && npm install @mui/styles
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_REACT }}
      - name: Generate build for React
        run: cd frontend/ && npm run build
      - name: Put built assets in Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: react-build
          path: frontend/build
  deploy:
    runs-on: ubuntu-latest  
    needs: build
    steps:
      - name: Fetch built assets from Artifacts
        uses: actions/download-artifact@v1
        with:
          name: react-build
          path: build
      - name: Display structure of downloaded files
        run: ls -R
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_NODE }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git clone https://github.com/aungkothet/minibank
            cd backend/
            npm install
            pm2 restart app


        